name: Xcode - Build and Analyze

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        env:
          scheme: ${{ 'default' }}
        run: |
          xcodebuild clean build test -workspace App/QuizApp.xcworkspace -scheme "CI" -destination"platform=iOS Simulator,OS=15.2,name=iPhone 8" ONLY_ACTIVE_ARCH=NO CODE_SINING_REQUIRED=NO | xcpretty && exit ${PIPESTATUS[0]}
